config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    
    resources :users do
      member do
        get :following, to: "follows#following"
        get :followers, to: "follows#followers"
      end
    end
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(index show destroy)
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create, destroy)
  end 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to t("layouts.application.about"), about_path %></li>
      <li><%= link_to t("layouts.application.contact"), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts._header.sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layouts.application.home"), root_path %></li>
        <li><%= link_to t("layouts.application.help"), help_path %></li>
        <% if logged_in? %>
          <li>
            <%= link_to t("layouts._header.users"), users_path %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "layouts._header.account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to t("layouts._header.profile"), current_user %>
              </li>
              <li>
                <%= link_to t("layouts._header.settings"), edit_user_path(current_user) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t("layouts._header.log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t("layouts._header.log_in"), login_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_layout.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= render "layouts/rails_layout" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= link_to t(".language_en"), locale: "en" %>
    <%= link_to t(".language_vi"), locale: "vi" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= debug(params) if Rails.env.development? %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>"
      I18n.locale = "<%= I18n.locale || I18n.default_locale %>"
    </script>
  </body>
</html>